version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=Bib52211443
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/bibsite
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  redis-server:
    image: redis:latest
    hostname: redis-server
    ports:
      - "6379:6379"


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: celery worker --app=belogo_new --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis-server
    depends_on:
      - redis-server


  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - web

  flower:
    build: .
    command:  flower -A belogo_new --port=5555 --broker=redis://redis-server:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER=redis://redis-server:6379/0
      - CELERY_BACKEND=redis://redis-server:6379/0
    depends_on:
      - web
      - redis-server
      - worker




