version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=Bib52211443
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/bibsite
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - web

  redis-server:
    image: redis:alpine
    hostname: redis-server

  worker:
    build:
      context: .
    command: celery -A belogo_new worker -l info
    depends_on:
      - redis-server

  celery-beat:
    build:
      context: .
    command: celery -A belogo_new beat -l info
    depends_on:
      - redis-server

  flower:
    build:
      context: .
    hostname: flower
    command: celery -A belogo_new flower
    depends_on:
      - redis-server
    ports:
      - "5555:5555"




