version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=Bib52211443
    volumes:
    - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/bibsite
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb

  redis-server:
    image: redis:latest
    hostname: redis-server
    ports:
      - "6379:6379"


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A belogo_new.celery.app worker -l INFO
    volumes:
      - ./service:/service
    links:
      - redis-server
    depends_on:
      - redis-server


  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
    - "80:80"
    depends_on:
      - web

  flower:
    image: mher/flower
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A belogo_new.celery.app flower
    volumes:
      - ./service:/service
    links:
      - redis-server
      - worker
    depends_on:
      - redis-server
      - worker
    ports:
      - "5555:5555"




