# Generated by Django 3.2.20 on 2023-08-09 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import email_signals.models
import mptt.fields
import utils.uploading


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование анонса')),
                ('description', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=False, verbose_name='Виден на главной?')),
            ],
            options={
                'verbose_name': 'Анонс',
                'verbose_name_plural': 'Анонсы библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library', models.CharField(choices=[('Информационно-культурный центр (Пролетарская 8)', 'Информационно-культурный центр (Пролетарская 8)'), ('Центр детского и семейного чтения (Пролетарская 8)', 'Центр детского и семейного чтения (Пролетарская 8)'), ('Бибилиотека эстетического развития (Керамик)', 'Бибилиотека эстетического развития (Керамик)'), ('Библиотека №2 (Саввино)', 'Библиотека №2 (Саввино)'), ('Библиотека №4 (Павлино)', 'Библиотека №4 (Павлино)'), ('Библиотека №3 (Кучино)', 'Библиотека №3 (Кучино)')], max_length=150, verbose_name='Выбор Библиотеки')),
                ('age', models.CharField(blank=True, choices=[('Дошкольники', 'Дошкольники'), ('Начальные классы', 'Начальные классы'), ('Старшие классы', 'Старшие классы')], max_length=50, null=True, verbose_name='Выбор возраста')),
                ('school', models.CharField(blank=True, choices=[('Гимназия №1', 'Гимназия №1'), ('Гимназия №2', 'Гимназия №2'), ('Гимназия №11', 'Гимназия №11'), ('Школа №5', 'Школа №5'), ('Школа №7', 'Школа №7'), ('Школа №10', 'Школа №10'), ('Школа №14', 'Школа №14'), ('Школа №15', 'Школа №15'), ('Прочие', 'Прочие')], max_length=50, null=True, verbose_name='Выбор школы/гимназии')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('bilet', models.CharField(blank=True, max_length=18, verbose_name='№ читательского билета')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='Номер елефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Е-мэйл')),
                ('comment', models.TextField(max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Форма продления книг',
                'verbose_name_plural': 'Формы продления книг',
            },
            bases=(models.Model, email_signals.models.EmailSignalMixin),
        ),
        migrations.CreateModel(
            name='Bookrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Е-мэйл')),
                ('comment', models.TextField(max_length=350, verbose_name='Список книг')),
            ],
            options={
                'verbose_name': 'Комплектование',
                'verbose_name_plural': 'Комплектование',
            },
            bases=(models.Model, email_signals.models.EmailSignalMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='тема кинозала')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Темы кинозала',
            },
        ),
        migrations.CreateModel(
            name='CinemaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День киносеанса')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Афиша кинозала',
                'verbose_name_plural': 'Афиша кинозала',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день ИКЦ',
                'verbose_name_plural': 'Расписание ИКЦ',
            },
        ),
        migrations.CreateModel(
            name='DayBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день БЭР',
                'verbose_name_plural': 'Расписание БЭР',
            },
        ),
        migrations.CreateModel(
            name='DayCDSCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день ЦДСЧ',
                'verbose_name_plural': 'Расписание ЦДСЧ',
            },
        ),
        migrations.CreateModel(
            name='DayF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Ф2',
                'verbose_name_plural': 'Расписание Ф2',
            },
        ),
        migrations.CreateModel(
            name='DayF3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Ф3',
                'verbose_name_plural': 'Расписание Ф3',
            },
        ),
        migrations.CreateModel(
            name='DayF4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Ф4',
                'verbose_name_plural': 'Расписание Ф4',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название события')),
                ('library', models.CharField(choices=[('Информационно-культурный центр (Пролетарская 8)', 'Информационно-культурный центр (Пролетарская 8)'), ('Центр детского и семейного чтения (Пролетарская 8)', 'Центр детского и семейного чтения (Пролетарская 8)'), ('Бибилиотека эстетического развития (Керамик)', 'Бибилиотека эстетического развития (Керамик)'), ('Библиотека №2 (Саввино)', 'Библиотека №2 (Саввино)'), ('Детская библиотека (Павлино)', 'Детская библиотека (Павлино)'), ('Библиотека №4 (Павлино)', 'Библиотека №4 (Павлино)'), ('Библиотека №3 (Кучино)', 'Библиотека №3 (Кучино)')], default='Информационно-культурный центр (Пролетарская 8)', max_length=150, verbose_name='Выбор Библиотеки')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата проведения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='HeroMemoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/tyl', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Герой книги памяти',
                'verbose_name_plural': 'Герои книги памяти',
            },
        ),
        migrations.CreateModel(
            name='LeningradResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/lg', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные жителя Блокадного Лениграда',
                'verbose_name_plural': 'Жители Блокадного Ленинграда',
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категория электронной библиотеки',
                'verbose_name_plural': 'Категории электронной библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/partners', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('block', models.CharField(blank=True, max_length=1, verbose_name='Номер блока')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Service_dop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('ed_izm', models.CharField(blank=True, max_length=100, verbose_name='Время/кол-во')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceDop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Е-мэйл')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, null=True, upload_to='img/files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Форма дополнительной услуги',
                'verbose_name_plural': 'Формы дополнительных услуг',
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Системное расписание')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата версии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Системное расписание',
                'verbose_name_plural': 'Системные расписания',
            },
        ),
        migrations.CreateModel(
            name='VeteranTruda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/tyl', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Труженик тыла',
                'verbose_name_plural': 'Труженики тыла',
            },
        ),
        migrations.CreateModel(
            name='VeteranVOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/vov', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные ветерана',
                'verbose_name_plural': 'Ветераны ВОВ',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание ИКЦ',
                'verbose_name_plural': 'Расписание ИКЦ',
            },
        ),
        migrations.CreateModel(
            name='WeekBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание БЭР',
                'verbose_name_plural': 'Расписание БЭР',
            },
        ),
        migrations.CreateModel(
            name='WeekCDSCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание ЦДСЧ',
                'verbose_name_plural': 'Расписание ЦДСЧ',
            },
        ),
        migrations.CreateModel(
            name='WeekF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Ф2',
                'verbose_name_plural': 'Расписание Ф2',
            },
        ),
        migrations.CreateModel(
            name='WeekF3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Ф3',
                'verbose_name_plural': 'Расписание Ф3',
            },
        ),
        migrations.CreateModel(
            name='WeekF4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Ф4',
                'verbose_name_plural': 'Расписание Ф4',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('salary', models.CharField(max_length=5, verbose_name='Оклад')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/vacancy', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Правила пользования',
                'verbose_name_plural': 'Правила пользования',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('time', models.CharField(blank=True, max_length=3, verbose_name='Время')),
                ('ed_izm', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raitings', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Оценка качества',
                'verbose_name_plural': 'Оценки качества',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Е-мэйл')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='Номер телефона')),
                ('comment', models.TextField(verbose_name='Вопрос')),
                ('category', models.ForeignKey(blank=True, default='Вопрос библиотекарю', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос библиотекарю',
                'verbose_name_plural': 'Вопросы библиотекарю',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость сайта',
                'verbose_name_plural': 'Новости сайта',
                'default_related_name': 'news',
            },
        ),
        migrations.CreateModel(
            name='Movi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='img/books/images', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на PDF файл')),
                ('file', models.FileField(blank=True, upload_to='img/books/files', verbose_name='Файл')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.author', verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.librarycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Электронная книга',
                'verbose_name_plural': 'Электонные книги',
            },
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Галерея изображений',
                'verbose_name_plural': 'Галерея изображений',
            },
        ),
        migrations.CreateModel(
            name='FreeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Бесплатные услуги',
                'verbose_name_plural': 'Бесплатные услуги',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Е-мэйл')),
                ('phone', models.CharField(blank=True, max_length=17, verbose_name='Номер телефона')),
                ('comment', models.TextField(max_length=350, verbose_name='Комментарий')),
                ('category', models.ForeignKey(blank=True, default='Форма обратной связи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='EventyF4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayf4', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventyF3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayf3', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventyF2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayf2', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventyCDSCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycdsch', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventyBER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayber', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Eventy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.day', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='web.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='dayf4',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekf4', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayf3',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekf3', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayf2',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekf2', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daycdsch',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekcdsch', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayber',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekber', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.week', verbose_name='Неделя'),
        ),
        migrations.CreateModel(
            name='Biblioteka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('phone', models.CharField(default='+7 (495) 555-55-55', max_length=18, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Емэйл')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='страница в ВКонтакте')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='страница в Одноклассниках')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='аккаунт Телеграмм')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/cbs', verbose_name='Фото')),
                ('worktime', models.CharField(blank=True, default='09:00 - 21:00', max_length=50, verbose_name='Время работы')),
                ('workdays', models.CharField(blank=True, default='Понедельник-Пятница', max_length=50, verbose_name='Рабочие дни')),
                ('worktime_alt', models.CharField(blank=True, default='09:00 - 21:00', max_length=50, verbose_name='Время работы')),
                ('workdays_alt', models.CharField(blank=True, default='Суббота-Воскресенье', max_length=50, verbose_name='Рабочие дни')),
                ('weekend', models.CharField(blank=True, default='Воскресенье', max_length=50, verbose_name='Выходной')),
                ('adress', models.CharField(max_length=250, verbose_name='Адрес')),
                ('primary', models.BooleanField(default=False, verbose_name='Основное подразделение')),
                ('map', models.URLField(blank=True, null=True, verbose_name='Ссылка на карту')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
                ('direktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='web.position', verbose_name='Должность')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='web.employers', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Библиотека/Филиал',
                'verbose_name_plural': 'Библиотеки/Филиалы',
            },
        ),
    ]
