# Generated by Django 3.2 on 2021-04-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteka',
            options={'verbose_name': 'Библиотека/Филиал', 'verbose_name_plural': 'Библиотеки/Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='partners',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на сайт'),
        ),
    ]
