# Generated by Django 3.2.20 on 2023-08-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230810_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Неделя киносеансов',
                'verbose_name_plural': 'Недели киносеансов',
            },
        ),
    ]
