# Generated by Django 3.2 on 2021-04-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210427_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='direktor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='страница в Фейсбуке'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='страница в Инстаграме'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='phone',
            field=models.CharField(default='+7 (495) 555-55-55', max_length=18, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='vk',
            field=models.URLField(blank=True, verbose_name='страница в ВК'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='workdays',
            field=models.CharField(blank=True, max_length=50, verbose_name='Рабочие дни'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='worktime',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото'),
        ),
    ]
