# Generated by Django 3.2 on 2021-05-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210428_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_title',
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='workdays',
            field=models.CharField(blank=True, default='Вт-Вск', max_length=50, verbose_name='Рабочие дни'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='worktime',
            field=models.CharField(blank=True, default='09:00 - 21:00', max_length=50, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название новости'),
        ),
    ]
