# Generated by Django 3.2.20 on 2023-08-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cinemaweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День киносеанса')),
                ('date', models.DateField(verbose_name='Дата')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.cinemaweek', verbose_name='Неделя киноафишы')),
            ],
            options={
                'verbose_name': 'День сеансов',
                'verbose_name_plural': 'Дни сеансов',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='web.cinemaday', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
