# Generated by Django 3.2.20 on 2023-08-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_cinemaday_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='day',
            new_name='cinemaday',
        ),
        migrations.RemoveField(
            model_name='cinemaday',
            name='week',
        ),
        migrations.AddField(
            model_name='cinemaday',
            name='cinemaweek',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cinemadays', to='web.cinemaweek', verbose_name='Неделя киноафишы'),
            preserve_default=False,
        ),
    ]
