# Generated by Django 3.2 on 2021-05-12 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210511_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='тема кинозала')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Кинозал',
                'verbose_name_plural': 'Темы кинозала',
            },
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
