# Generated by Django 3.2.20 on 2023-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20230810_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemaday',
            options={'verbose_name': 'День сеансов ИКЦ', 'verbose_name_plural': 'Дни сеансов ИКЦ'},
        ),
        migrations.AlterModelOptions(
            name='cinemaweek',
            options={'verbose_name': 'Неделя киносеансов ИКЦ', 'verbose_name_plural': 'Недели киносеансов ИКЦ'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Рабочий день ИКЦ', 'verbose_name_plural': 'Рабочий день ИКЦ'},
        ),
        migrations.AlterModelOptions(
            name='dayber',
            options={'verbose_name': 'Рабочий день БЭР', 'verbose_name_plural': 'Рабочий день БЭР'},
        ),
        migrations.AlterModelOptions(
            name='daycdsch',
            options={'verbose_name': 'Рабочий день ЦДСЧ', 'verbose_name_plural': 'Рабочий день ЦДСЧ'},
        ),
        migrations.AlterModelOptions(
            name='dayf2',
            options={'verbose_name': 'Рабочий день Ф2', 'verbose_name_plural': 'Рабочие дни Ф2'},
        ),
        migrations.AlterModelOptions(
            name='dayf3',
            options={'verbose_name': 'Рабочий день Ф3', 'verbose_name_plural': 'Рабочий день Ф3'},
        ),
        migrations.AlterModelOptions(
            name='dayf4',
            options={'verbose_name': 'Рабочий день Ф4', 'verbose_name_plural': 'Рабочий день Ф4'},
        ),
        migrations.AlterModelOptions(
            name='eventy',
            options={'verbose_name': 'Мероприятие ИКЦ', 'verbose_name_plural': 'Мероприятия ИКЦ'},
        ),
        migrations.AlterModelOptions(
            name='eventyber',
            options={'verbose_name': 'Мероприятие БЭР', 'verbose_name_plural': 'Мероприятия БЭР'},
        ),
        migrations.AlterModelOptions(
            name='eventycdsch',
            options={'verbose_name': 'Мероприятие ЦДСЧ', 'verbose_name_plural': 'Мероприятия ЦДСЧ'},
        ),
        migrations.AlterModelOptions(
            name='eventyf2',
            options={'verbose_name': 'Мероприятие Ф2', 'verbose_name_plural': 'Мероприятия Ф2'},
        ),
        migrations.AlterModelOptions(
            name='eventyf3',
            options={'verbose_name': 'Мероприятие Ф3', 'verbose_name_plural': 'Мероприятия Ф3'},
        ),
        migrations.AlterModelOptions(
            name='eventyf4',
            options={'verbose_name': 'Мероприятие Ф4', 'verbose_name_plural': 'Мероприятия Ф4'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм ИКЦ', 'verbose_name_plural': 'Фильмы ИКЦ'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'verbose_name': 'Расписание ИКЦ', 'verbose_name_plural': 'Расписания ИКЦ'},
        ),
        migrations.AlterModelOptions(
            name='weekber',
            options={'verbose_name': 'Расписание БЭР', 'verbose_name_plural': 'Расписания БЭР'},
        ),
        migrations.AlterModelOptions(
            name='weekcdsch',
            options={'verbose_name': 'Расписание ЦДСЧ', 'verbose_name_plural': 'Расписания ЦДСЧ'},
        ),
        migrations.AlterModelOptions(
            name='weekf2',
            options={'verbose_name': 'Расписание Ф2', 'verbose_name_plural': 'Расписания Ф2'},
        ),
        migrations.AlterModelOptions(
            name='weekf3',
            options={'verbose_name': 'Расписание Ф3', 'verbose_name_plural': 'Расписания Ф3'},
        ),
        migrations.AlterModelOptions(
            name='weekf4',
            options={'verbose_name': 'Расписание Ф4', 'verbose_name_plural': 'Расписания Ф4'},
        ),
        migrations.AddField(
            model_name='eventy',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='eventy',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
        migrations.AddField(
            model_name='eventyber',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='eventyber',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
        migrations.AddField(
            model_name='eventycdsch',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='eventycdsch',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
        migrations.AddField(
            model_name='eventyf2',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='eventyf2',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
        migrations.AddField(
            model_name='eventyf3',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='eventyf3',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
        migrations.AddField(
            model_name='eventyf4',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='eventyf4',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
    ]
