# Generated by Django 3.2.20 on 2023-11-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20231027_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventy',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='eventyber',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='eventycdsch',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='eventyf2',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='eventyf3',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='eventyf4',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Запись'),
        ),
    ]
