# Generated by Django 3.2 on 2021-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteka',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='страница в Фейсбуке'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='страница в Инстаграме'),
        ),
    ]
