# Generated by Django 3.2.20 on 2023-12-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20231101_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='category',
        ),
    ]
