# Generated by Django 3.2 on 2021-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210519_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteka',
            name='facebook',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='страница в Фейсбуке'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='instagram',
            field=models.URLField(blank=True, default='#', null=True, verbose_name='страница в Инстаграме'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='vk',
            field=models.URLField(blank=True, default='#', verbose_name='страница в ВК'),
        ),
    ]
