# Generated by Django 3.2.20 on 2024-01-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_event_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
