# Generated by Django 3.2.20 on 2024-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20240212_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polojeniekonkurs',
            name='konkurs_doc',
            field=models.FileField(blank=True, null=True, upload_to='documents/polojenie_k', verbose_name='Файл положения'),
        ),
        migrations.AlterField(
            model_name='polojeniekonkurs',
            name='konkurs_zayavka',
            field=models.FileField(blank=True, null=True, upload_to='documents/polojeni_k_z', verbose_name='Файл Заявки'),
        ),
    ]
