# Generated by Django 3.2 on 2021-05-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='web.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликована'),
        ),
    ]
