# Generated by Django 3.2.20 on 2024-02-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20240212_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polojeniekonkurs',
            name='category',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polojenya_konkurs', to='web.category', verbose_name='Категория'),
        ),
    ]
