# Generated by Django 3.2.20 on 2024-02-13 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_polojeniekonkurs_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.AddField(
            model_name='library',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='polojeniekonkurs',
            name='category',
            field=models.ForeignKey(blank=True, default=16, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polojenya_konkurs', to='web.category', verbose_name='Категория'),
        ),
    ]
