# Generated by Django 3.2 on 2021-05-25 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210524_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edizm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Еденица измерения',
                'verbose_name_plural': 'Еденицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Service_dop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('ed_izm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.edizm', verbose_name='Ед. изм.')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
            },
        ),
        migrations.CreateModel(
            name='Service_dop_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('fio', models.CharField(default='Иванов Иван Иванович', max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, default='8 (965) 999 99 99', max_length=17)),
                ('email', models.EmailField(max_length=254, verbose_name='Емэйл')),
                ('comment', models.TextField(default='Ваш комментарий или список книг для продления', max_length=300, verbose_name='Комментарий')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.service_dop', verbose_name='Выбор услуги')),
            ],
            options={
                'verbose_name': 'Форма дополнительной услуги',
                'verbose_name_plural': 'Формы дополнительных услуг',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Емэйл')),
                ('phone', models.CharField(blank=True, default='8 (965) 999 99 99', max_length=17)),
                ('comment', models.TextField(verbose_name='Вопрос')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос библиотекарю',
                'verbose_name_plural': 'Вопросы библиотекарю',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Емэйл')),
                ('phone', models.CharField(blank=True, default='8 (965) 999 99 99', max_length=17)),
                ('comment', models.TextField(verbose_name='Вопрос')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='web.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='Иванов Иван Иванович', max_length=200, verbose_name='ФИО')),
                ('bilet', models.IntegerField(default='1234567891234', verbose_name='№ читательского билета')),
                ('phone', models.CharField(blank=True, default='8 (965) 999 99 99', max_length=17)),
                ('email', models.EmailField(max_length=254, verbose_name='Емэйл')),
                ('comment', models.TextField(default='Ваш комментарий или список книг для продления', max_length=300, verbose_name='Комментарий')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Форма продления книг',
                'verbose_name_plural': 'Формы продления книг',
            },
        ),
    ]
