# Generated by Django 3.2.20 on 2024-02-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20240213_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='created_at',
        ),
    ]
