# Generated by Django 3.2 on 2021-05-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_book_edizm_employers_feedback_position_question_service_dop_service_dop_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteka',
            name='direktor',
        ),
    ]
