# Generated by Django 3.2 on 2021-05-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_biblioteka_direktor'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='direktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='web.employers', verbose_name='Руководитель'),
        ),
    ]
