# Generated by Django 3.2 on 2021-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_biblioteka_direktor'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Основное подразделение'),
        ),
    ]
