# Generated by Django 3.2.20 on 2024-02-27 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_bookview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие(персональные данные)'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие(персональные данные)'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие(персональные данные)'),
        ),
        migrations.AddField(
            model_name='question',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие(персональные данные)'),
        ),
        migrations.AddField(
            model_name='servicedop',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие(персональные данные)'),
        ),
        migrations.AlterField(
            model_name='bookview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.library', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookview',
            name='view_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество просмотров книги'),
        ),
        migrations.AlterField(
            model_name='bookview',
            name='viewed_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата просмотра'),
        ),
    ]
