# Generated by Django 3.2.20 on 2024-03-25 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20240227_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Дата проведения'),
        ),
    ]
