# Generated by Django 3.2 on 2021-05-25 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210525_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employers',
            old_name='position',
            new_name='positions',
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='direktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position', to='web.employers', verbose_name='Руководитель'),
        ),
    ]
