# Generated by Django 3.2 on 2021-05-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20210525_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employers',
            old_name='positions',
            new_name='doljnosti',
        ),
    ]
