# Generated by Django 3.2.20 on 2024-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20240327_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(blank=True, default=models.DateTimeField(verbose_name='Дата и время начала'), verbose_name='Дата и время окончания'),
        ),
    ]
