# Generated by Django 3.2 on 2021-05-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_rename_positions_employers_doljnosti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employers',
            name='doljnosti',
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='web.employers', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='employers',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer', to='web.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='direktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='web.position', verbose_name='Должность'),
        ),
    ]
