# Generated by Django 3.2 on 2021-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20210526_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Емэйл'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='страница в Фейсбуке'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='страница в Инстаграме'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='vk',
            field=models.URLField(blank=True, verbose_name='страница в ВК'),
        ),
    ]
