# Generated by Django 3.2 on 2021-06-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20210526_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bilet',
            field=models.IntegerField(max_length='13', verbose_name='№ читательского билета'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default='Продление книг', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория'),
        ),
    ]
