# Generated by Django 3.2.4 on 2021-06-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_auto_20210607_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bilet',
            field=models.IntegerField(verbose_name='№ читательского билета'),
        ),
    ]
