# Generated by Django 3.2.20 on 2024-03-27 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_event_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время окончания'),
        ),
    ]
