# Generated by Django 3.2.4 on 2021-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20210610_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bilet',
            field=models.IntegerField(blank=True, verbose_name='№ читательского билета'),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='book',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
