# Generated by Django 3.2.4 on 2021-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20210610_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bilet',
            field=models.CharField(blank=True, max_length=18, verbose_name='№ читательского билета'),
        ),
    ]
