# Generated by Django 3.2.20 on 2024-03-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_alter_event_date_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='link',
            new_name='link_pdf',
        ),
    ]
