# Generated by Django 3.2.4 on 2021-06-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_book_bilet'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликованно'),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(blank=True, default='Форма обратной связи', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default='Вопрос библиотекарю', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.category', verbose_name='Категория'),
        ),
    ]
