# Generated by Django 3.2.20 on 2024-03-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_rename_link_library_link_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='link_pdf',
            new_name='pdf_url',
        ),
    ]
