# Generated by Django 3.2.4 on 2021-06-11 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20210611_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default='Продление книг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='web.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(blank=True, default='Форма обратной связи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='web.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default='Вопрос библиотекарю', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='web.category', verbose_name='Категория'),
        ),
    ]
