# Generated by Django 3.2.20 on 2024-03-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_rename_link_pdf_library_pdf_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='pdf_url',
            new_name='link',
        ),
    ]
