# Generated by Django 3.2.20 on 2024-04-05 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_rename_pdf_url_library_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название темы проектов')),
            ],
            options={
                'verbose_name': 'Тема проектов',
                'verbose_name_plural': 'Темы проектов',
            },
        ),
        migrations.AlterField(
            model_name='eventy',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.day', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата')),
                ('file', models.FileField(blank=True, upload_to='media/projects', verbose_name='Файл')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на PDF')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.library', verbose_name='Выбор Библиотеки')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projecttheme', verbose_name='Тема проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
