# Generated by Django 3.2.20 on 2024-04-05 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20240405_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.biblioteka', verbose_name='Выбор Библиотеки'),
        ),
    ]
