# Generated by Django 3.2.4 on 2021-09-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_document_qualityrating_vacancy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
