# Generated by Django 3.2.20 on 2024-04-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_project_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='web.biblioteka', verbose_name='Библиотека'),
        ),
    ]
