# Generated by Django 3.2.4 on 2021-09-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_rename_partners_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='block',
            field=models.CharField(blank=True, max_length=1, verbose_name='Номер блока'),
        ),
    ]
