# Generated by Django 3.2.4 on 2021-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_partner_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/docs', verbose_name='Скан документа'),
        ),
    ]
