# Generated by Django 3.2.20 on 2024-07-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_news_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayB5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Библиотеки №5',
                'verbose_name_plural': 'Рабочий день Библиотеки №5',
            },
        ),
        migrations.CreateModel(
            name='DayBCJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день ЦГБ им. Тютчева',
                'verbose_name_plural': 'Рабочий день БЦ Южный',
            },
        ),
        migrations.CreateModel(
            name='DayBSCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день БСЧ им Дмитриева',
                'verbose_name_plural': 'Рабочий БСЧ им Дмитриева',
            },
        ),
        migrations.CreateModel(
            name='DayCGBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день ЦГБ им. Тютчева',
                'verbose_name_plural': 'Рабочий день ЦГБ им. Тютчева',
            },
        ),
        migrations.CreateModel(
            name='DayCSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Черновская сельская библиотека',
                'verbose_name_plural': 'Рабочий день Черновская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Детская библиотека',
                'verbose_name_plural': 'Рабочий день Детская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayDBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Детская библиотека (Твардовского)',
                'verbose_name_plural': 'Рабочий день Детская библиотека (Твардовского)',
            },
        ),
        migrations.CreateModel(
            name='DayFSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Федурновская сельская библиотека',
                'verbose_name_plural': 'Рабочий день Федурновская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Никольско-Архангельская библиотека',
                'verbose_name_plural': 'Рабочий день Никольско-Архангельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Никольская библиотека',
                'verbose_name_plural': 'Рабочий день Никольская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayNMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Новомилетская сельская библиотека',
                'verbose_name_plural': 'Рабочий день Новомилетская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayPPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Пехра-Покровская библиотека',
                'verbose_name_plural': 'Рабочий день Пехра-Покровская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DaySSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Соболихинская сельская библиотека',
                'verbose_name_plural': 'Рабочий день Соболихинская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='DayYB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Рабочий день Юношеская библиотека',
                'verbose_name_plural': 'Рабочий день Юношеская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekB5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Библиотеки №5',
                'verbose_name_plural': 'Расписания Библиотеки №5',
            },
        ),
        migrations.CreateModel(
            name='WeekBCJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание БЦ Южный',
                'verbose_name_plural': 'Расписания БЦ Южный',
            },
        ),
        migrations.CreateModel(
            name='WeekBSCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание БСЧ им Дмитриева',
                'verbose_name_plural': 'Расписания БСЧ им Дмитриева',
            },
        ),
        migrations.CreateModel(
            name='WeekCGBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание ЦГБ им. Тютчева',
                'verbose_name_plural': 'Расписания ЦГБ им. Тютчева',
            },
        ),
        migrations.CreateModel(
            name='WeekCSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Черновская сельская библиотека',
                'verbose_name_plural': 'Расписания Черновская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Детская библиотека',
                'verbose_name_plural': 'Расписания Детская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekDBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Детская библиотека (Твардовского)',
                'verbose_name_plural': 'Расписания Детская библиотека (Твардовского)',
            },
        ),
        migrations.CreateModel(
            name='WeekFSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Федурновская сельская библиотека',
                'verbose_name_plural': 'Расписания Федурновская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Никольско-Архангельская библиотека',
                'verbose_name_plural': 'Расписания Никольско-Архангельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Никольская библиотека',
                'verbose_name_plural': 'Расписания Никольская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekNMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Новомилетская сельская библиотека',
                'verbose_name_plural': 'Расписания Новомилетская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekPPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Пехра-Покровская библиотека',
                'verbose_name_plural': 'Расписания Пехра-Покровская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekSSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Соболихинская сельская библиотека',
                'verbose_name_plural': 'Расписания Соболихинская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='WeekYB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Первое число недели')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Последнее число недели')),
                ('active', models.BooleanField(default=False, verbose_name='Текущая рабочая неделя')),
            ],
            options={
                'verbose_name': 'Расписание Юношеская библиотека',
                'verbose_name_plural': 'Расписания Юношеская библиотека',
            },
        ),
        migrations.AlterField(
            model_name='eventy',
            name='age',
            field=models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycdsch', verbose_name='День недели'),
        ),
        migrations.CreateModel(
            name='EventyYB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayyb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Юношеская библиотека',
                'verbose_name_plural': 'Мероприятия Юношеская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventySSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayssb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Соболихинская сельская библиотека',
                'verbose_name_plural': 'Мероприятия Соболихинская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyPPB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayppb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Пехра-Покровская библиотека',
                'verbose_name_plural': 'Мероприятия Пехра-Покровская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyNMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daynmb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Новомилетская сельская библиотека',
                'verbose_name_plural': 'Мероприятия Новомилетская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daynb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Никольская библиотека',
                'verbose_name_plural': 'Мероприятия Никольская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daynab', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Никольско-Архангельская библиотека',
                'verbose_name_plural': 'Мероприятия Никольско-Архангельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyFSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayfsb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Федурновская сельская библиотека',
                'verbose_name_plural': 'Мероприятия Федурновская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyDBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daydbt', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Детская библиотека (Твардовского)',
                'verbose_name_plural': 'Мероприятия Детская библиотека (Твардовского)',
            },
        ),
        migrations.CreateModel(
            name='EventyDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daydb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Детская библиотека',
                'verbose_name_plural': 'Мероприятия Детская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyCSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycsb', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Черновская сельская библиотека',
                'verbose_name_plural': 'Мероприятия Черновская сельская библиотека',
            },
        ),
        migrations.CreateModel(
            name='EventyCGBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycgbt', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие ЦГБ им. Тютчева',
                'verbose_name_plural': 'Мероприятия ЦГБ им. Тютчева',
            },
        ),
        migrations.CreateModel(
            name='EventyBSCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daybscd', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие БСЧ им Дмитриева',
                'verbose_name_plural': 'Мероприятия БСЧ им Дмитриева',
            },
        ),
        migrations.CreateModel(
            name='EventyBCJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daybcj', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие БЦ Южный',
                'verbose_name_plural': 'Мероприятия БЦ Южный',
            },
        ),
        migrations.CreateModel(
            name='EventyB5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('payment', models.BooleanField(default=False, verbose_name='Платное')),
                ('booking', models.BooleanField(default=False, verbose_name='Запись')),
                ('age', models.CharField(blank=True, choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], max_length=50, null=True, verbose_name='Возраст')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayb5', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Мероприятие Библиотеки №5',
                'verbose_name_plural': 'Мероприятия Библиотеки №5',
            },
        ),
        migrations.AddField(
            model_name='dayyb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekyb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayssb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekssb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayppb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekppb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daynmb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weeknmb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daynb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weeknb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daynab',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weeknab', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayfsb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekfsb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daydbt',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekdbt', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daydb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekdb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daycsb',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekcsb', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daycgbt',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekcgbt', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daybscd',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekbscd', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='daybcj',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekbcj', verbose_name='Неделя'),
        ),
        migrations.AddField(
            model_name='dayb5',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='web.weekb5', verbose_name='Неделя'),
        ),
    ]
