# Generated by Django 3.2.20 on 2024-08-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20240702_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daybcj',
            options={'verbose_name': 'Рабочий день БЦ Южный', 'verbose_name_plural': 'Рабочий день БЦ Южный'},
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='media/documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.day', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycdsch', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='age',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('16+', '16+'), ('18+', '18+'), ('55+', '55+'), ('60+', '60+'), ('65+', '65+')], default='0+', max_length=50, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала'),
        ),
    ]
