# Generated by Django 3.2.4 on 2021-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_alter_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
