# Generated by Django 3.2.20 on 2024-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20240821_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='img/cbs', verbose_name='QR-код'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/projects', verbose_name='Файл'),
        ),
    ]
