# Generated by Django 3.2.4 on 2021-10-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_vacancy_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='QualityRating',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница сайта', 'verbose_name_plural': 'Страницы сайта'},
        ),
        migrations.AddField(
            model_name='page',
            name='salary',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Оклад'),
        ),
        migrations.AddField(
            model_name='page',
            name='vacancy_description',
            field=models.TextField(blank=True, null=True, verbose_name='Требования к вакансии'),
        ),
    ]
