# Generated by Django 3.2.8 on 2021-10-12 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20211011_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость сайта',
                'verbose_name_plural': 'Новости сайта',
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raitings', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Оценка качества',
                'verbose_name_plural': 'Оценки качества',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('salary', models.CharField(max_length=5, verbose_name='Оклад')),
                ('description', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news', verbose_name='Главное фото')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='web.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
