# Generated by Django 3.2.20 on 2025-04-10 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20241107_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект года', 'verbose_name_plural': 'Проекты года'},
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.day', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventy',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayb5', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyb5',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daybcj', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventybcj',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyber',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayber', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daybscd', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventybscd',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycdsch', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventycdsch',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycgbt', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventycgbt',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daycsb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventycsb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daydb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventydb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daydbt', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventydbt',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayf2', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyf2',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayf3', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyf3',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayf4', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyf4',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayfsb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyfsb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daynab', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventynab',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daynb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventynb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.daynmb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventynmb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayppb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyppb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayssb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyssb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='web.dayyb', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='end_time',
            field=models.TimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='eventyyb',
            name='start_time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.projecttheme', verbose_name='Общая тема проекта'),
        ),
        migrations.CreateModel(
            name='Project_other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/projects/img', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Название')),
                ('date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата')),
                ('file_pdf', models.FileField(blank=True, upload_to='media/projects', verbose_name='Файл pdf')),
                ('file', models.FileField(blank=True, upload_to='media/projects', verbose_name='Файл (разное)')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на PDF')),
                ('library', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.biblioteka', verbose_name='Выбор Библиотеки')),
            ],
            options={
                'verbose_name': 'Наш проект',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
