# Generated by Django 3.2 on 2021-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20211012_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(blank=True, max_length=3, verbose_name='Время'),
        ),
    ]
