# Generated by Django 3.2 on 2021-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ed_izm',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service_dop',
            name='ed_izm',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Edizm',
        ),
    ]
