# Generated by Django 3.2 on 2021-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20211014_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_dop',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цена'),
        ),
    ]
