# Generated by Django 3.2 on 2021-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_alter_service_dop_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цена'),
        ),
    ]
