# Generated by Django 3.2 on 2021-10-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_alter_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Бесплатные услуги',
                'verbose_name_plural': 'Бесплатные услуги',
            },
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(verbose_name='Текст')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Правила пользования',
                'verbose_name_plural': 'Правила пользования',
            },
        ),
    ]
