# Generated by Django 3.2 on 2021-10-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_freeservice_termsofuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeservice',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='termsofuse',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
