# Generated by Django 3.2 on 2021-10-21 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_alter_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата проведения'),
        ),
    ]
