# Generated by Django 3.2 on 2021-10-21 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Системное расписание')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата версии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Системное расписание',
                'verbose_name_plural': 'Системные расписания',
            },
        ),
    ]
