# Generated by Django 3.2 on 2021-10-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_shedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(max_length=350, verbose_name='Вопрос'),
        ),
    ]
