# Generated by Django 3.2 on 2021-10-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0048_alter_feedback_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='map',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на карту'),
        ),
    ]
