# Generated by Django 3.2 on 2021-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_biblioteka_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/vacancy', verbose_name='Главное фото'),
        ),
    ]
