# Generated by Django 3.2 on 2021-10-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0050_alter_vacancy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeningradResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/lg', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные жителя Блокадного Лениграда',
                'verbose_name_plural': 'Жители Блокадного Ленинграда',
            },
        ),
        migrations.CreateModel(
            name='VeteranTruda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/trud', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные ветерана труда',
                'verbose_name_plural': 'Ветераны Труда',
            },
        ),
        migrations.CreateModel(
            name='VeteranVOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/vov', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Данные ветерана',
                'verbose_name_plural': 'Ветераны ВОВ',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
