# Generated by Django 3.2 on 2021-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_auto_20211025_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMemoryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/veterans/tyl', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Герой книги памяти',
                'verbose_name_plural': 'Герои книги памяти',
            },
        ),
        migrations.AlterModelOptions(
            name='veterantruda',
            options={'verbose_name': 'Труженик тыла', 'verbose_name_plural': 'Труженики тыла'},
        ),
        migrations.AlterField(
            model_name='veterantruda',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/veterans/tyl', verbose_name='Фото'),
        ),
    ]
