# Generated by Django 3.2 on 2021-10-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_auto_20211025_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service_dop_form',
            new_name='ServiceDopForm',
        ),
    ]
