# Generated by Django 3.2 on 2021-10-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_rename_servicedopform_servicedop'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedop',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dopservices', to='web.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='book',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Е-мэйл'),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Номер елефона'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(max_length=350, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Е-мэйл'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Е-мэйл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='servicedop',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='servicedop',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Е-мэйл'),
        ),
        migrations.AlterField(
            model_name='servicedop',
            name='fio',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='servicedop',
            name='phone',
            field=models.CharField(blank=True, max_length=17, verbose_name='Номер телефона'),
        ),
    ]
