# Generated by Django 3.2 on 2021-10-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_auto_20211026_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_dop',
            name='ed_izm',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время/кол-во'),
        ),
    ]
