# Generated by Django 3.2 on 2021-10-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0056_alter_service_dop_ed_izm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedop',
            name='category',
            field=models.ForeignKey(blank=True, default='Форма для услуг', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dopservices', to='web.category', verbose_name='Категория'),
        ),
    ]
