# Generated by Django 3.2 on 2021-10-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0057_alter_servicedop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedop',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
