# Generated by Django 3.2 on 2021-10-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_anons'),
    ]

    operations = [
        migrations.AddField(
            model_name='anons',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Виден на главной?'),
        ),
    ]
