# Generated by Django 3.2 on 2021-12-07 08:36

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('web', '0061_auto_20211207_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Галерея изображений', 'verbose_name_plural': 'Галерея изображений'},
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='name',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='use_in_slider',
            field=models.BooleanField(default=False, verbose_name='Использовать в слайдере'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to=utils.uploading.upload_function),
        ),
    ]
