# Generated by Django 3.2 on 2022-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0064_remove_imagegallery_use_in_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteka',
            name='weekend',
            field=models.CharField(blank=True, default='Воскресенье', max_length=50, verbose_name='Выходной'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='workdays_alt',
            field=models.CharField(blank=True, default='Суббота-Воскресенье', max_length=50, verbose_name='Рабочие дни'),
        ),
        migrations.AddField(
            model_name='biblioteka',
            name='worktime_alt',
            field=models.CharField(blank=True, default='09:00 - 21:00', max_length=50, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='biblioteka',
            name='workdays',
            field=models.CharField(blank=True, default='Понедельник-Пятница', max_length=50, verbose_name='Рабочие дни'),
        ),
    ]
