"""
Django settings for belogo_new project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
import environ

env = environ.Env()
environ.Env.read_env('.env')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qgj-94qz%*=o+4byxx%##qoy*wx$luxs0%_rp$#!i1_!*%)9jt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'biblioteka-belogo.ru', 'www.biblioteka-belogo.ru', '213.141.153.187']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web',
    'easy_thumbnails',
    'filer',
    'mptt',
    'ckeditor',
    'ckeditor_uploader',
    'crispy_forms',
    'import_export',
    'admin_reorder'
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


ADMIN_REORDER = (
    # НОВОСТИ
    {'app': 'web', 'label': 'НОВОСТИ',
     'models': ('web.News', 'web.Anons')
     },
    # ГЛАВНАЯ СТРАНИЦА
    {'app': 'web', 'label': 'ГЛАВНАЯ СТРАНИЦА',
     'models': ('web.Event', 'web.Cinema', 'web.Shedule', 'web.Partner')
    },
    # БИБЛИОТЕКИ
    {'app': 'web', 'label': 'БИБЛИОТЕКА',
     'models': ('web.Biblioteka', 'web.Document', 'web.Raiting', 'web.Vacancy')
    },
    # УСЛУГИ
    {'app': 'web', 'label': 'УСЛУГИ',
     'models': ('web.Service', 'web.FreeService', 'web.TermsOfUse',)
    },
    # ВЕТЕРАНЫ
    {'app': 'web', 'label':'ВЕТЕРАНЫ',
     'models': ('web.VeteranVOV', 'web.VeteranTruda', 'web.LeningradResident',)
     },
    # ФОРМЫ
    {'app': 'alcohol', 'label': 'ФОРМЫ',
     'models': ('web.Book', 'web.Question', 'web.Feedback', 'web.Service_dop',)
     },
    # СПРАВОЧНИКИ
    {'app': 'web', 'label':'СПРАВОЧНИКИ',
     'models': ('web.Position', 'web.Employers', 'web.Category',)
     }
)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',
]

ROOT_URLCONF = 'belogo_new.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'belogo_new.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.sqlite3',
       'NAME': BASE_DIR / 'db.sqlite3',
   }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': env("POSTGRES_DB"),
#         'USER': env("POSTGRES_USER"),
#         'PASSWORD': env("POSTGRES_PASSWORD"),
#         'HOST': env("POSTGRES_HOST"),
#         'PORT': env("POSTGRES_PORT")
#     }
# }

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'site@biblioteka-belogo.ru'
EMAIL_HOST_PASSWORD = 'Bib5221144'
EMAIL_USE_TLS = True

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    (BASE_DIR / 'static_dev'),
)

# Media files
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'extraPlugins': 'lightbox_filer',
        'toolbar': 'full',
        'forcePasteAsPlainText': True,
        'allowedContent': True,
    },
}


